### ISSUE TITLE
Which _templates.csv to use?

### ISSUE THREAD

**Issue by Giermann** [john30/ebusd-configuration#7]
I'm goind to play around with ebusd and started with the latest 2.0.0-preview. So I grabbed the config files from here but I find 2 different _templates.csv:

ebusd-2.x.x\de\_templates.csv
ebusd-2.x.x\de\vaillant\_templates.csv

I started using the one in "vaillant", since I'm going to read from my Vaillant system, but this does not match the rest of the CSVs. I had to add at least some temp/bday/percent templates. But now I found the other file, which is way shorter but includes those.
Which one is right?

**Comment by john30** [comment]
You need both templates. Just point the configuration directory to the "de" folder, and ebusd loads the global templates from that directory as well as the vaillant specific ones from the vaillant directory.
It is even easier if you use the "--scanconfig" option, since the necessary files will then be picked automatically by ebusd after scanning each seen device.
