### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by danielkucera** [john30/ebusd-configuration#85]
Hi,

what physical unit represent this value? kWh? m3? Joule?
And where do you get the mappings?

https://github.com/john30/ebusd-configuration/blob/58c7e6d22d16bdf39ad1a3e1754c1191dc11cbec/ebusd-2.1.x/en/vaillant/bai.0010015600.inc#L164

Thanks.

**Comment by john30** [comment]
I don't know! The data is from a mysterious database :-)

**Comment by danielkucera** [comment]
I installed a sensor to my gas meter and I guess 1 unit can correspond to 0.5 Joules. What do you think?

391.29M - 390.63M = 0.66M
73.95M - 73.92M = 0.03M
0.66 + 0.03 = 0.69M

3.43 - 2.6 = 0.83 m3
0.83*10.55 = 8.76065 kWh
8.76065 * 3 600 000 = 31.53834 MJ

![screenshot from 2018-03-17 20-01-25](https://user-images.githubusercontent.com/1734256/37559196-d2807f0c-2a21-11e8-94de-26f0814b5344.png)

**Comment by john30** [comment]
I really don't know. seems to be a linear factor though

**Comment by andig** [comment]
@danielkucera hope this is not too off-topic. If you want to log/monitor something like counter values I can recomment volkszaehler.org to you (me being one of the developers):

<img width="1144" alt="screen shot 2018-03-18 at 14 28 18" src="https://user-images.githubusercontent.com/184815/37566404-e54dade8-2ab8-11e8-8597-2043e36072f3.png">

The units are still wrong as per your post above but the current consumption is being displayed instead of the counter values.

**Comment by danielkucera** [comment]
@andig No, thank you. I'm using zabbix and it works fine.

**Comment by Dinth** [comment]
Has anyone managed to find a good way of conversion of vaillant units to kWh/m3?

**Comment by sylvaing** [comment]
@danielkucera you confirm that vaillant unit it's 0.5 joules ?

**Comment by danielkucera** [comment]
I can't.
